# -*- coding: utf-8 -*-
"""banco.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGq93WHzpqNxwQNdUco3ftLrauNY0DOs
"""

print("menu".center(14,"="))
menu = '''
  [0] - Depositar
  [1] - Saque
  [2] - Extrato
  [3] - Sair
  '''
saldo = 0
limite = 500
extrato = ""
numero_saques = 0
LIMITE_SAQUES = 3

while True:
  opcao = input(menu)
  if opcao == "0":
    valor = float(input("Valor do depósito: "))
    if valor > 0:
      saldo += valor
      extrato += f"Depósito: R$ {valor:.2f}\n"
    else:
      print("Valor inválido para depósito.")
  elif opcao == "1":
    valor = float(input("Valor do saque: "))
    sem_saldo = valor > saldo
    sem_limite = valor > limite
    saques_indisponivel = numero_saques >= LIMITE_SAQUES
    if sem_saldo:
      print("Você não tem saldo.")
    elif sem_limite:
      print("O valor é maior que o limite.")
    elif saques_indisponivel:
      print("Número máximo de saques excedido.")
    else:
      saldo -= valor
      extrato += f"Saque: R$ {valor:.2f}\n"
      numero_saques += 1
  elif opcao == "2":
    print("EXTRATO".center(14,"="))
    print("Não foram realizadas transações." if not extrato else extrato)
    print(f"\nSaldo: R$ {saldo:.2f}")
    print("=" * 14)
    break
  elif opcao == "3":
    break
  else:
    print("Operação inválida, por favor selecione novamente a operação desejada.")

